"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Profile = { id: string; vasectomy_date: string; target_ejaculation_count: number; waiting_period_months: number; notes: string | null };
const EVENT_TYPES = [
  { value: "masturbation", label: "Masturbación" },
  { value: "regular_sex", label: "Sexo regular" },
  { value: "oral_sex", label: "Sexo oral" },
  { value: "partner_manual", label: "Manual por pareja" },
] as const;
type EventType = (typeof EVENT_TYPES)[number]["value"];
type Event = { id: string; occurred_at: string; event_type: EventType; note: string | null };
const eventTypeLabel = (type: EventType) => EVENT_TYPES.find(item => item.value === type)?.label || type;
const dateInput = (d: Date) => { const tz = d.getTimezoneOffset() * 60000; return new Date(d.getTime() - tz).toISOString().slice(0, 16); };
const calendarDate = (d = new Date()) => { const local = new Date(d.getTime() - d.getTimezoneOffset() * 60000); return local.toISOString().slice(0, 10); };
const addMonths = (date: string, months: number) => { const [y, m, d] = date.split("-").map(Number); const result = new Date(Date.UTC(y, m - 1 + months, d)); return result.toISOString().slice(0, 10); };
const niceDate = (date: string) => new Intl.DateTimeFormat("en-US", { month: "long", day: "numeric", year: "numeric" }).format(new Date(`${date}T12:00:00`));
const daysBetween = (from: string, to: string) => Math.max(0, Math.ceil((new Date(`${to}T12:00:00`).getTime() - new Date(`${from}T12:00:00`).getTime()) / 86400000));

export default function Page() {
  const [userId, setUserId] = useState<string | null>(null); const [profile, setProfile] = useState<Profile | null>(null); const [events, setEvents] = useState<Event[]>([]); const [view, setView] = useState<"home" | "history" | "calendar" | "settings">("home"); const [toast, setToast] = useState(""); const [editing, setEditing] = useState<Event | null>(null); const [adding, setAdding] = useState(false); const [accessError, setAccessError] = useState("");
  const load = async () => { let { data: { user } } = await supabase.auth.getUser(); if (!user) { const { data, error } = await supabase.auth.signInAnonymously(); if (error || !data.user) { setAccessError(error?.message || "Unable to open your private tracker."); return; } user = data.user; } setAccessError(""); setUserId(user.id); const [p, e] = await Promise.all([supabase.from("profiles").select("*").single(), supabase.from("events").select("*").order("occurred_at", { ascending: false })]); if (p.data) setProfile(p.data); if (e.data) setEvents(e.data); };
  useEffect(() => { load(); if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => undefined); const { data: { subscription } } = supabase.auth.onAuthStateChange(() => load()); return () => subscription.unsubscribe(); }, []);
  const flash = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2800); };
  if (!userId) return <main className="grid min-h-screen place-items-center px-6 text-center text-muted">{accessError || "Opening your private tracker…"}</main>;
  if (!profile) return <main className="grid min-h-screen place-items-center text-muted">Loading your tracker…</main>;
  const eligibilityDate = addMonths(profile.vasectomy_date, profile.waiting_period_months); const today = calendarDate(); const countDone = events.length >= profile.target_ejaculation_count; const timeDone = today >= eligibilityDate; const percent = Math.min(100, Math.round((events.length / profile.target_ejaculation_count) * 100)); const status = countDone && timeDone ? "READY FOR FOLLOW-UP SEMEN ANALYSIS" : countDone ? "COUNT COMPLETE — WAITING FOR TIME REQUIREMENT" : timeDone ? "TIME REQUIREMENT COMPLETE — MORE EVENTS REQUIRED" : "IN PROGRESS";
  async function addEvent(event_type: EventType) { const { data, error } = await supabase.from("events").insert({ user_id: userId, occurred_at: new Date().toISOString(), event_type }).select().single(); if (error) return flash(error.message); if (data) setEvents(es => [data, ...es]); setAdding(false); flash("Evento registrado"); }
  async function remove(id: string, ask = true) { if (ask && !confirm("Delete this event?")) return; const { error } = await supabase.from("events").delete().eq("id", id); if (!error) { setEvents(es => es.filter(x => x.id !== id)); flash(ask ? "Event deleted" : "Most recent event undone"); } else flash(error.message); }
  async function undo() { const recent = events[0]; if (recent) await remove(recent.id, false); }
  async function saveEvent(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!editing) return; const form = new FormData(e.currentTarget); const occurred_at = new Date(String(form.get("occurred_at"))).toISOString(); const note = String(form.get("note") || "") || null; const event_type = String(form.get("event_type")) as EventType; const { data, error } = await supabase.from("events").update({ occurred_at, note, event_type }).eq("id", editing.id).select().single(); if (error) return flash(error.message); setEvents(es => es.map(x => x.id === editing.id ? data : x).sort((a,b) => +new Date(b.occurred_at) - +new Date(a.occurred_at))); setEditing(null); flash("Evento actualizado"); }
  async function saveSettings(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const update = { vasectomy_date: String(f.get("vasectomy_date")), target_ejaculation_count: Number(f.get("target")), waiting_period_months: Number(f.get("waiting")), notes: String(f.get("notes") || "") || null }; const { data, error } = await supabase.from("profiles").update(update).eq("id", userId).select().single(); if (error) return flash(error.message); setProfile(data); flash("Settings saved"); }
  return <main className="mx-auto min-h-[100svh] max-w-md px-4 pb-28 pt-[max(1rem,env(safe-area-inset-top))]"><header className="mb-6"><p className="label">Private tracker</p><h1 className="text-xl font-semibold">Your progress</h1></header>
    {view === "home" && <Home profile={profile} events={events} eligibilityDate={eligibilityDate} countDone={countDone} timeDone={timeDone} percent={percent} status={status} today={today} onAdd={() => setAdding(true)} onUndo={undo} />}
    {view === "history" && <History events={events} onEdit={setEditing} onDelete={remove} />}
    {view === "calendar" && <Calendar events={events} />}
    {view === "settings" && <Settings profile={profile} onSave={saveSettings} />}
    <nav className="fixed bottom-0 left-1/2 z-10 flex w-full max-w-md -translate-x-1/2 justify-around border-t border-white/10 bg-[#101114]/95 px-2 pb-[max(.75rem,env(safe-area-inset-bottom))] pt-3 backdrop-blur">{([['home','Progress'],['history','History'],['calendar','Calendar'],['settings','Settings']] as const).map(([key, label]) => <button key={key} onClick={() => setView(key)} className={`min-w-16 rounded-xl px-2 py-2 text-xs ${view === key ? 'bg-white/10 text-accent' : 'text-muted'}`}>{label}</button>)}</nav>
    {toast && <div className="fixed bottom-24 left-1/2 z-20 -translate-x-1/2 rounded-full bg-accent px-5 py-3 text-sm font-semibold text-ink shadow-xl">{toast}</div>}
    {adding && <div className="fixed inset-0 z-30 grid place-items-end bg-black/60 p-4"><section className="w-full max-w-md rounded-3xl bg-panel p-6"><p className="label">Registrar evento</p><h2 className="mt-1 text-xl font-semibold">Selecciona el tipo</h2><div className="mt-5 grid gap-3">{EVENT_TYPES.map(type => <button key={type.value} onClick={() => addEvent(type.value)} className="rounded-2xl border border-white/10 bg-white/5 px-5 py-4 text-left font-medium active:bg-accent active:text-ink">{type.label}</button>)}</div><button onClick={() => setAdding(false)} className="mt-4 w-full py-3 text-sm text-muted">Cancelar</button></section></div>}
    {editing && <div className="fixed inset-0 z-30 grid place-items-end bg-black/60 p-4"><form onSubmit={saveEvent} className="w-full max-w-md rounded-3xl bg-panel p-6"><h2 className="text-xl font-semibold">Editar evento</h2><label className="label mt-5 block">Tipo<select className="field" name="event_type" defaultValue={editing.event_type}>{EVENT_TYPES.map(type => <option key={type.value} value={type.value}>{type.label}</option>)}</select></label><label className="label mt-4 block">Fecha y hora<input className="field" name="occurred_at" type="datetime-local" defaultValue={dateInput(new Date(editing.occurred_at))} required /></label><label className="label mt-4 block">Nota opcional<textarea className="field min-h-20" name="note" defaultValue={editing.note || ""} /></label><div className="mt-5 flex gap-3"><button type="button" onClick={() => setEditing(null)} className="flex-1 rounded-2xl border border-white/10 py-3 text-sm">Cancelar</button><button className="flex-1 rounded-2xl bg-accent py-3 text-sm font-bold text-ink">Guardar</button></div></form></div>}
  </main>;
}

function Home({ profile, events, eligibilityDate, countDone, timeDone, percent, status, today, onAdd, onUndo }: { profile: Profile; events: Event[]; eligibilityDate: string; countDone: boolean; timeDone: boolean; percent: number; status: string; today: string; onAdd: () => void; onUndo: () => void }) { const remaining = Math.max(0, profile.target_ejaculation_count - events.length); const since = daysBetween(profile.vasectomy_date, today); const left = daysBetween(today, eligibilityDate); return <div className="space-y-4"><section className="card border-accent/30 bg-gradient-to-br from-[#242b1a] to-panel"><p className="label text-accent">{status}</p><p className="mt-3 text-sm leading-6 text-white/70">Your follow-up becomes available when both the event and time requirements are complete.</p></section><section className="card"><p className="label">Ejaculation progress</p><div className="mt-2 flex items-end gap-2"><strong className="text-6xl font-semibold tracking-tighter">{events.length}</strong><span className="mb-2 text-2xl text-muted">/ {profile.target_ejaculation_count}</span></div><p className="label mt-1">Ejaculations</p><div className="mt-5 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-accent transition-all" style={{ width: `${percent}%` }} /></div><div className="mt-3 flex justify-between text-sm text-muted"><span>{percent}% complete</span><span>{remaining} remaining</span></div></section><button onClick={onAdd} className="w-full rounded-3xl bg-accent py-5 text-lg font-bold text-ink shadow-[0_12px_35px_rgba(184,240,90,.16)]">+ REGISTER EVENT</button>{events[0] && <button onClick={onUndo} className="w-full text-sm text-muted underline underline-offset-4">Undo most recent event</button>}<section className="card"><p className="label">Time progress</p><div className="mt-4 space-y-4 text-sm"><Info label="Vasectomy date" value={niceDate(profile.vasectomy_date)} /><Info label="Days since vasectomy" value={`${since} days`} /><Info label="Follow-up eligibility date" value={niceDate(eligibilityDate)} /><Info label="Time remaining" value={timeDone ? "Requirement complete" : `${left} days remaining`} /></div></section><section className="card"><p className="label mb-4">Ready for semen analysis requirements</p><Check done={countDone} title={`${profile.target_ejaculation_count} ejaculation events`} detail={`${events.length} / ${profile.target_ejaculation_count} completed`} /><Check done={timeDone} title={`${profile.waiting_period_months} months after vasectomy`} detail={`Available ${niceDate(eligibilityDate)}`} /></section></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4"><span className="text-muted">{label}</span><span className="text-right font-medium">{value}</span></div>; }
function Check({ done, title, detail }: { done: boolean; title: string; detail: string }) { return <div className="mb-4 flex gap-3 last:mb-0"><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-full text-sm ${done ? 'bg-accent text-ink' : 'border border-white/30 text-muted'}`}>{done ? '✓' : '○'}</span><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-muted">{detail}</p></div></div>; }
function History({ events, onEdit, onDelete }: { events: Event[]; onEdit: (e: Event) => void; onDelete: (id: string) => void }) { return <section><h2 className="mb-4 text-2xl font-semibold">Historial</h2>{events.length === 0 ? <div className="card text-sm text-muted">Aún no hay eventos registrados.</div> : <><EventTypeChart events={events} /><div className="mt-4 space-y-3">{events.map(e => <article className="card flex items-center justify-between gap-3" key={e.id}><div><p className="font-medium">{new Intl.DateTimeFormat("es-MX", { dateStyle: "medium", timeStyle: "short" }).format(new Date(e.occurred_at))}</p><p className="mt-1 text-sm text-accent">{eventTypeLabel(e.event_type)}</p>{e.note && <p className="mt-1 text-sm text-muted">{e.note}</p>}</div><div className="flex gap-2"><button onClick={() => onEdit(e)} className="rounded-lg bg-white/10 px-3 py-2 text-xs">Editar</button><button onClick={() => onDelete(e.id)} className="rounded-lg bg-red-400/10 px-3 py-2 text-xs text-red-300">Borrar</button></div></article>)}</div></>}</section>; }
function EventTypeChart({ events }: { events: Event[] }) {
  const colors: Record<EventType, string> = { masturbation: "#b8f05a", regular_sex: "#8db8ff", oral_sex: "#d7a7ff", partner_manual: "#ffb870" };
  const totals = EVENT_TYPES.map(type => ({ ...type, count: events.filter(event => event.event_type === type.value).length, color: colors[type.value] }));
  let angle = 0; const stops = totals.filter(item => item.count > 0).map(item => { const start = angle; angle += item.count / events.length * 360; return `${item.color} ${start}deg ${angle}deg`; });
  return <section className="card"><div className="flex items-baseline justify-between"><div><p className="label">Acumulado por tipo</p><h3 className="mt-1 text-lg font-semibold">{events.length} eventos registrados</h3></div></div><div className="mt-5 flex items-center gap-5"><div className="relative grid h-36 w-36 shrink-0 place-items-center rounded-full" role="img" aria-label="Gráfica de pastel por tipo de evento" style={{ background: `conic-gradient(${stops.join(", ")})` }}><div className="grid h-20 w-20 place-items-center rounded-full bg-panel text-center"><strong className="text-2xl">{events.length}</strong><span className="text-[10px] uppercase tracking-wider text-muted">Total</span></div></div><div className="min-w-0 flex-1 space-y-2">{totals.map(item => <div className="flex items-center justify-between gap-2 text-xs" key={item.value}><span className="flex min-w-0 items-center gap-2"><i className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ background: item.color }} /><span className="truncate">{item.label}</span></span><span className="font-semibold">{item.count}</span></div>)}</div></div></section>;
}
function Calendar({ events }: { events: Event[] }) { const [cursor, setCursor] = useState(new Date()); const first = new Date(cursor.getFullYear(), cursor.getMonth(), 1); const offset = first.getDay(); const days = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 0).getDate(); const active = useMemo(() => new Set(events.map(e => calendarDate(new Date(e.occurred_at)))), [events]); const cells = Array.from({ length: offset + days }, (_, i) => i < offset ? null : i - offset + 1); return <section><div className="mb-4 flex items-center justify-between"><button onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() - 1, 1))} className="rounded-xl bg-white/10 px-4 py-2">‹</button><h2 className="text-xl font-semibold">{cursor.toLocaleString("en-US", { month: "long", year: "numeric" })}</h2><button onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1))} className="rounded-xl bg-white/10 px-4 py-2">›</button></div><div className="card"><div className="grid grid-cols-7 text-center text-xs text-muted">{["S","M","T","W","T","F","S"].map((d,i) => <div className="pb-3" key={i}>{d}</div>)}</div><div className="grid grid-cols-7 gap-y-2">{cells.map((d,i) => { const key = d ? `${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,"0")}-${String(d).padStart(2,"0")}` : "empty" + i; return <div key={key} className="grid aspect-square place-items-center">{d && <span className={`grid h-9 w-9 place-items-center rounded-full text-sm ${active.has(key) ? 'bg-accent font-bold text-ink' : ''}`}>{d}</span>}</div>; })}</div><p className="mt-4 text-center text-xs text-muted">Green dates have registered events.</p></div></section>; }
function Settings({ profile, onSave }: { profile: Profile; onSave: (e: FormEvent<HTMLFormElement>) => void }) { return <section><h2 className="mb-4 text-2xl font-semibold">Settings</h2><form onSubmit={onSave} className="card space-y-4"><label className="label block">Vasectomy date<input className="field" name="vasectomy_date" type="date" defaultValue={profile.vasectomy_date} required /></label><label className="label block">Target ejaculation count<input className="field" name="target" type="number" min="1" defaultValue={profile.target_ejaculation_count} required /></label><label className="label block">Required waiting period (months)<input className="field" name="waiting" type="number" min="1" defaultValue={profile.waiting_period_months} required /></label><label className="label block">Private notes<textarea className="field min-h-28" name="notes" defaultValue={profile.notes || ""} placeholder="Optional" /></label><button className="w-full rounded-2xl bg-accent py-4 font-bold text-ink">Save settings</button></form></section>; }
